
apiVersion: v1
kind: Service
metadata:
  namespace: my-namespace
  labels:
    app: myservice
  name: myservice
spec:
  ports:
  - name: bakehouseport
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Release.Name }}
  type: NodePort
status:
  loadBalancer: {}
